### PR TITLE
First Server apache 2.4 is up and running :-)

### PR DESCRIPTION
**Pull request by jerger**
Hi Dave,

now I managed to bring my first webserver up and running. So I think I've reached a valid point.
We can discuss my changes and think about how to reintegrate my work, if you've some time.

Curious waiting for your feedback and with best regards,
Michael

### CODE REVIEW

**Comment by upgradingdave** [comment]
Thanks Michael, this is great. I'll try and merge this in with my code next week.

Thanks again!
Dave

**Comment by jerger** [comment]
Hi Dave,

how are u? Do you need support for reintegrate my pull requests?

In meantime, I added some more features (support for http-proxy & basic authentication). I also added some bugfixes. Maybe that's usefull to you also?

Best regards,
Michael

**Comment by upgradingdave** [comment]
Hi Michael, thanks again for this! I've been busy with work and family, but will try and merge this in asap. 

Thanks!
Dave

**Comment by upgradingdave** [comment]
Hi Michael, I took your changes and tried to refactor a bit to eliminate duplication and hopefully keep this library as simple and easy to use as possible. 

I think it's coming along pretty nicely! The tests are all still passing, so hopefully I didn't break anything. 

I especially like how you updated the vhost generation code - it's a nice way to be able to easily write complex vhost files, very cool. 

Here's a few notes about what I refactored. I hope this all works for you, please let me know what you think:

- moved vhost fn's from config.clj to vhost.clj
- config.clj now contains useful/convenient samples
- combined httpd.clj and apache2.clj
- updated README
- removed src/httpd/groups (the README has the examples now)
- moved apache2 cmd line fn's into cmds.clj
- added the jclouds dependency back so I could test with aws
- removed sysstat related code (I think it would be simpler to keep only apache httpd, here and maybe create another crate for sysstate). 
- removed the eclipse files (I like to try and keep all specific IDE conf files out of version control as much as possible, hope that doesn't mess you up too much)

**Comment by jerger** [comment]
Hi Dave,

cool :-) in order to stay in sync I will try a pull back or consider an refork (I never tryed this before - so it would take some days on my side ;).

Regarding your notes:

> moved vhost fn's from config.clj to vhost.clj
> config.clj now contains useful/convenient samples
> combined httpd.clj and apache2.clj

Excellent. I allready thougt about this steps, but leaved the decission up to you. 
So it's great to see the same ideas at your side :-)

> moved apache2 cmd line fn's into cmds.clj

Good idea - great :-)

> added the jclouds dependency back so I could test with aws

Can you imagine other alternatives at this point? 
I work mainly with existing nodes, so I don't need jclouds in all constellations. 
If http crate enforce this dependency, it's not the real vision. What do you think about?

> removed sysstat related code (I think it would be simpler to keep only apache httpd, here and maybe create another crate for sysstate).

Yes, your right - I agree :-)

> removed the eclipse files (I like to try and keep all specific IDE conf files out of version control as much as possible, hope that doesn't mess you up too much)

Okay - I completly agree :-)

**Comment by upgradingdave** [comment]
Hi Michael, that all sounds good. 

I moved the jclouds libs into a leiningen profile called `:aws` and that way jclouds shouldn't get in your way. 

Also, here are the commands I think you can use to update your branch with mine. First, setup a new remote called "upstream": 

     git remote add upstream https://github.com/upgradingdave/httpd-crate.git

Then fetch all changes

    git fetch

I like to create a "tracking branch" like this: 

    git checkout -b upstream upstream/master

Then, it should be able to merge cleanly like so:

    git checkout master  # switch back to your master branch
    git merge upstream  # merge changes from remote tracking branch named 'upstream'

Or, you can also force your repository's master branch to the latest commit on my master like this: 

    git checkout master
    git reset --hard upstream

Hope that helps!

Dave

**Comment by jerger** [comment]
Worked like a charm ... thanx :-)

**Pull request merged**
